# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pairwise_chisq_cpp <- function(mat, resp, min_prop = 0.05, max_prop = 0.95, chisq_cutoff = 0.01, diff_cutoff = 0.0, min_valid_prop = 0.5) {
    .Call(`_PairMarker_pairwise_chisq_cpp`, mat, resp, min_prop, max_prop, chisq_cutoff, diff_cutoff, min_valid_prop)
}

